#!/bin/bash
PHARO_VM=${PHARO_VM:-./pharo}
PILLAR_IMAGE=${PILLAR_IMAGE:-./Pharo.image}

command=$1
shift

# disable parameter expansion to forward all arguments unprocessed to the VM
set -f

exec "$PHARO_VM" "$PILLAR_IMAGE" pillar "$command" --baseDirectory="$(pwd)" "$@"
